const lucide = require("lucide-react");
console.log("Sidebar:", !!lucide.Sidebar);
console.log("PanelLeft:", !!lucide.PanelLeft);
console.log("PanelLeftClose:", !!lucide.PanelLeftClose);
console.log("PanelLeftOpen:", !!lucide.PanelLeftOpen);
console.log("SidebarClose:", !!lucide.SidebarClose);
console.log("SidebarOpen:", !!lucide.SidebarOpen);
console.log("ToggleLeft:", !!lucide.ToggleLeft);
console.log("ToggleRight:", !!lucide.ToggleRight);
console.log("SplitView:", !!lucide.SplitView);
console.log("SplitSquareHorizontal:", !!lucide.SplitSquareHorizontal);
console.log("SplitSquareVertical:", !!lucide.SplitSquareVertical);
console.log("SquareSplitHorizontal:", !!lucide.SquareSplitHorizontal);
